### ISSUE TITLE
Project update 1

### ISSUE THREAD

**Issue by iasonmat** [sorensenbrook/BoardGame-Recommender#2]
For Project Update 1, we updated the README file, as well as (i) uploaded a Tasks document, with all we have to do for the project broken down in detail, (ii) uploaded our processed data, (iii) uploaded a first version of the model we are using.

**Comment by JoepAUC** [comment]
First, we divided task from the first phase among the three of us. 

Thereafter we worked on our own tasks individually. Occasionally we met to discuss how to connect our work in a smooth way or how our all parts should interplay. So far this is what we got: 


#### Joep (questionnaire, user interface):
Did some research on how to make and use graphical user interface using PySimpleGUI. This way can ask the question from the questionnaire and present the results in a user-friendly way. Furthermore, worked on how to extract key information which is necessary for the recommender system from user answers. (See code: extract_info_noun). Finally, worked a bit on which questions to ask in odor to get the user to give the right type of answers (see document: questionnaire).

#### Iason (data, GitHub):
Found and edited the appropriate data. From a Kaggle dataset with hundreds of categories, I made sub-selections and groupings which combine all the useful categories we have, such that there is a direct correspondence between our data and the features we want to extract. Also, I am in charge of updating GitHub with our project progress.

#### Brook (TM model, GitHub):       
Started making the user_to_feature model, to be tested further with the processed data that we collect. It also still needs to check and make sure that there is a word similiar enough and a way to deal with it when it is not. Also, created the GitHub page, and work on it regularly. Also looked into different user information that could be scrapped to test the recommender by comparing the wishlist of users to the recommended games.

**Comment by JoepKapma** [comment]
First, we divided task from the first phase among the three of us.
Thereafter we worked on our own tasks individually. Occasionally we met to discuss how to connect our work in a smooth way or how our all parts should interplay. So far this is what we got:


#### Joep (questionnaire, user interface):
Did some research on how to make and use graphical user interface using PySimpleGUI. This way we can ask the questions from the questionnaire (see questionnaire.md file) and present the results in a user-friendly way. Furthermore, I worked on how to extract key information from the user input, which is necessary for the recommender system. (See code: extract_info_noun). However, this is not yet producing the results which I like. Finally, worked a bit on which questions to ask in odor to get the user to give the right type of answers (see document: questionnaire.md).

#### Iason (data, GitHub):
Found and edited the appropriate data. From a Kaggle dataset with hundreds of categories, I made sub-selections and groupings which combine all the useful categories we have, such that there is a direct correspondence between our data and the features we want to extract. Also, I am in charge of updating GitHub with our project progress.

#### Brook (TM model, GitHub):
Started making the user_to_feature model, to be tested further with the processed data that we collect. It also still needs to check and make sure that there is a word similiar enough and a way to deal with it when it is not. Also, created the GitHub page, and work on it regularly. Also looked into different user information that could be scrapped to test the recommender by comparing the wishlist of users to the recommended games.\

#### Questions: 
Do you have advice on how to extract the correct information from the user’s input? If the user answers a question about which theme they like, how can I extract info only about the theme? Getting all nouns, filtering them and averaging their vectors is not producing accurate enough data yet.

**Comment by bloemj** [comment]
Looks good!

Right, we already talked a bit about your question. You need some sort of external data source to know what (kinds of) words are important and which are not. Perhaps you can have vectors of words that represent common themes and then see if any of the nouns in the user's input is close to those.
